import os

ABSPATH = os.path.dirname(os.path.abspath(__file__))

NUM_INPUT_MIN = 3
NUM_INPUT_MAX = 10
NUM_CONSTRAINT_MIN = 2
NUM_CONSTRAINT_MAX = 20

RANDOM_WITNESS_MIN = 0
RANDOM_WITNESS_MAX = 100

RANDOM_MATRIX_MIN = 0
RANDOM_MATRIX_MAX = 100000

MODULUS = 7001

SEED_INPUT = os.path.join(ABSPATH, "seed")
FUZZING_OUTPUT = os.path.join(ABSPATH, "fuzzmatrix")

LIBRARY = "LIBSNARK"

if (LIBRARY.upper() == "LIBSNARK"):
    LIBRARY_PATH = os.path.join(ABSPATH, "depends/libsnark-for-mfuzz")
# GENERATION FUZZING VALID MATRIX


# GENERATION FUZZING VALID MATRIX


# GENERATION FUZZING VALID MATRIX


# GENERATION FUZZING VALID MATRIX